services:

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
      args:
        PORT: 8080
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  postgres: { }

networks:
  backend:
    driver: bridge
